#import "HIDVirtualDeviceBridge.h"
#import <Foundation/Foundation.h>

// Import the Swift-generated header (generated by stage 1)
#import "VirtualFIDODevice-Swift.h"

hid_virtual_device_t hid_virtual_device_create(const char *device_name) {
  NSLog(@"[HIDVirtualDeviceBridge] hid_virtual_device_create called for %s",
        device_name);
  @autoreleasepool {
    NSString *name = [NSString stringWithUTF8String:device_name];
    NSError *error = nil;

    NSLog(@"[HIDVirtualDeviceBridge] Initializing VirtualFIDODevice...");
    VirtualFIDODevice *device =
        [[VirtualFIDODevice alloc] initWithDeviceName:name error:&error];

    if (error) {
      NSLog(@"[HIDVirtualDeviceBridge] Failed to create device: %@", error);
      return NULL;
    }

    // Activate the device
    [device activate];

    // Retain to keep alive
    CFRetain((__bridge CFTypeRef)device);
    return (__bridge void *)device;
  }
}

void hid_virtual_device_destroy(hid_virtual_device_t device) {
  if (device == NULL)
    return;

  @autoreleasepool {
    VirtualFIDODevice *fidoDevice =
        (__bridge_transfer VirtualFIDODevice *)device;
    // ARC will handle cleanup
    (void)fidoDevice;
  }
}

int hid_virtual_device_send_report(hid_virtual_device_t device,
                                   const uint8_t *data, size_t length) {
  if (device == NULL || data == NULL)
    return -1;

  @autoreleasepool {
    VirtualFIDODevice *fidoDevice = (__bridge VirtualFIDODevice *)device;
    NSData *reportData = [NSData dataWithBytes:data length:length];
    [fidoDevice sendReportWithData:reportData];
    return 0;
  }
}

void hid_virtual_device_set_callback(hid_virtual_device_t device,
                                     hid_report_callback_t callback) {
  if (device == NULL || callback == NULL)
    return;

  @autoreleasepool {
    VirtualFIDODevice *fidoDevice = (__bridge VirtualFIDODevice *)device;
    [fidoDevice setCallback:callback];
  }
}
